language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

services:
    - mysql

branches:
  only:
  - master
  - develop
  - feature/*

install:
  - sudo apt-get install -y pylint python3-mysqldb
  - sudo pip install -U pytest
  - sudo pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD:$PWD/mysql-wrapper/
  - mysql -u root < test_db.sql

# command to run tests
script:
  - echo "pylint --errors-only mysql-wrapper/*.py ... "
  - pylint --errors-only mysql-wrapper/*.py

#  - echo "pytest ... "
#  - pytest
 
  - echo "run mysqlwrapper.py ... "
  - python mysql-wrapper/mysqlwrapper.py

  - echo "run examples ... "
  - python test/example/basic_example.py
